### ISSUE TITLE
Minor Grammatical error

### ISSUE THREAD

**Issue by galahad42** [DevCassie/DevCassie#1]
There's one minor grammatical error in the [Personal](https://github.com/DevCassie#personal) section.

>👨 -> Pronounces are he and him

It should be `Pronouns`.

**Comment by DevCassie** [comment]
> There's one minor grammatical error in the [Personal](https://github.com/DevCassie#personal) section.
> 
> > 👨 -> Pronounces are he and him
> 
> It should be `Pronouns`.

Thanks for the heads up @galahad42 . I fixed it just now 😄
