### ISSUE TITLE
Minor Spelling Error

### ISSUE THREAD

**Issue by meenal21** [DevCassie/DevCassie#2]
Hey Cassie! I was going through your profile and spotted these two spelling mistakes in the last line in the Personal section.

> Yin yang enthousiast and I conider myself a Toaist 

You can change it to:
> Yin yang enthusiast and I consider myself a Toaist

**Comment by DevCassie** [comment]
> Hey Cassie! I was going through your profile and spotted these two spelling mistakes in the last line in the Personal section.
> 
> > Yin yang enthousiast and I conider myself a Toaist 
> 
> You can change it to:
> > Yin yang enthusiast and I consider myself a Toaist 

Thanks for letting me know @meenal21 !
